[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
GeoIO = "f5a160d5-e41d-4189-8b61-d57781c419e3"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
